remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

# site settings
title: 教學投影片
description: 收錄資料爬蟲、網頁開發、程式教學等課程投影片

# just-the-docs settings
color_scheme: dark
search_enabled: true

# footer
footer_content: "© 2025 Hao-Yun Chuang"

# build settings
markdown: kramdown

nav_external_links:
  - title: ⬅ Hao-Yun's Geekbase
    url: https://milanochuang.github.io
  - title: GitHub
    url: https://github.com/milanochuang
 
