plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
execute:
  execute_notebooks: force
  stderr_output: remove
  exclude_patterns:
    - 'homework1'
    - 'homework2'
    - 'homework3'

theme: jekyll-theme-minimal
